% HPV catch-up vaccination
function[dPop , hpvVaxd, hpvVaxdPrev, hpvVaxdNonPrev] = hpvVaxCU(pop , viral , risk , ...
    hpvVaxStates , hpvNonVaxStates , endpoints , intervens , vaxAgeCU , ...
    vaxCoverCU , vaxGCU , vaxDiseaseIndsCU , toInd)

%% Initialize dPop and output vectors
dPop = zeros(size(pop));
hpvVaxd = 0;
hpvVaxdPrev = 0; 
hpvVaxdNonPrev = 0; 

% Apply catch-up vaccination regimen
for dS = 1 : length(vaxDiseaseIndsCU)
    d = vaxDiseaseIndsCU(dS);
    for v = 1 : viral
        for g = min(vaxGCU) : max(vaxGCU) 
            for r = 1 : risk
                for aV = 1:length(vaxAgeCU) % apply appropriate coverage rate for each age group catch-up vaccinated    
                    a = vaxAgeCU(aV);
                    fromNonVSusCU_noScrn = toInd(allcomb(d , v , 1 , 1 : hpvNonVaxStates , 1 : 3 , 1 , ...
                        g , a , r)); 
                    fromNonVSusCU_scrn = toInd(allcomb(d , v , 1 , 1 : hpvNonVaxStates , 1 : 3 , 3 , ...
                        g , a , r)); 
                    fromNonVImmCU_noScrn = toInd(allcomb(d , v , 7 , 1 : hpvNonVaxStates , 1 : 3 , 1 , ...
                        g , a , r)); 
                    fromNonVImmCU_scrn = toInd(allcomb(d , v , 7 , 1 : hpvNonVaxStates , 1 : 3 , 3 , ...
                        g , a , r)); 
                    fromNonVCin1CU_noScrn = toInd(allcomb(d , v , 3 , 1 : hpvNonVaxStates , 1 : 3 , 1 , ...
                        g , a , r)); % HPV+, no screen
                    fromNonVCin1CU_scrn = toInd(allcomb(d , v , 3 , 1 : hpvNonVaxStates , 1 : 3 , 3 , ...
                        g , a , r)); % HPV+, screen
                    fromNonVCin2CU_noScrn = toInd(allcomb(d , v , 4 , 1 : hpvNonVaxStates , 1 : 3 , 1 , ...
                        g , a , r)); % HPV+, no screen
                    fromNonVCin2CU_scrn = toInd(allcomb(d , v , 4 , 1 : hpvNonVaxStates , 1 : 3 , 3 , ...
                        g , a , r)); % HPV+, screen
                    fromNonVCin3CU_noScrn = toInd(allcomb(d , v , 5 , 1 : hpvNonVaxStates , 1 : 3 , 1 , ...
                        g , a , r)); % HPV+, no screen
                    fromNonVCin3CU_scrn = toInd(allcomb(d , v , 5 , 1 : hpvNonVaxStates , 1 : 3 , 3 , ...
                        g , a , r)); % HPV+, screen
                    fromNonVCcCU_noScrn = toInd(allcomb(d , v , 6 , 1 : hpvNonVaxStates , 1 : 3 , 1 , ...
                        g , a , r)); % HPV+, no screen
                    fromNonVCcCU_scrn = toInd(allcomb(d , v , 6 , 1 : hpvNonVaxStates , 1 : 3 , 3 , ...
                        g , a , r)); % HPV+, screen
                    fromNonVInfCU_noScrn = toInd(allcomb(d , v , 2 , 1 : hpvNonVaxStates , 1 : 3 , 1 , ...
                        g , a , r)); % HPV+, no screen
                    fromNonVInfCU_scrn = toInd(allcomb(d , v , 2 , 1 : hpvNonVaxStates , 1 : 3 , 3 , ...
                        g , a , r)); % HPV+, screen
                    toVSusCU_noScrn = toInd(allcomb(d , v , 1 , 1 : hpvNonVaxStates , 1 : 3 , 2 , ...
                       g , a , r));
                    toVSusCU_scrn = toInd(allcomb(d , v , 1 , 1 : hpvNonVaxStates , 1 : 3 , 4 , ...
                       g , a , r));
                    toVImmCU_noScrn = toInd(allcomb(d , v , 7 , 1 : hpvNonVaxStates , 1 : 3 , 2 , ...
                       g , a , r));
                    toVImmCU_scrn = toInd(allcomb(d , v , 7 , 1 : hpvNonVaxStates , 1 : 3 , 4 , ...
                       g , a , r));
                    toVInfCU_scrn = toInd(allcomb(d , v , 2 , 1 : hpvNonVaxStates , 1 : 3 , 6 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    toVInfCU_noScrn = toInd(allcomb(d , v , 2 , 1 : hpvNonVaxStates , 1 : 3 , 5 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    toVCin1CU_scrn = toInd(allcomb(d , v , 3 , 1 : hpvNonVaxStates , 1 : 3 , 6 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    toVCin1CU_noScrn = toInd(allcomb(d , v , 3 , 1 : hpvNonVaxStates , 1 : 3 , 5 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    toVCin2CU_scrn = toInd(allcomb(d , v , 4 , 1 : hpvNonVaxStates , 1 : 3 , 6 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    toVCin2CU_noScrn = toInd(allcomb(d , v , 4 , 1 : hpvNonVaxStates , 1 : 3 , 5 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    toVCin3CU_scrn = toInd(allcomb(d , v , 5 , 1 : hpvNonVaxStates , 1 : 3 , 6 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    toVCin3CU_noScrn = toInd(allcomb(d , v , 5 , 1 : hpvNonVaxStates , 1 : 3 , 5 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    toVCcCU_scrn = toInd(allcomb(d , v , 6 , 1 : hpvNonVaxStates , 1 : 3 , 6 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    toVCcCU_noScrn = toInd(allcomb(d , v , 6 , 1 : hpvNonVaxStates , 1 : 3 , 5 , ...
                        g , a , r)); %into a vaccinated while HPV+ compartment, assigned to vaxxed in intervens
                    otherVCU = toInd(allcomb(d , v , 1 : hpvVaxStates , 1 : hpvNonVaxStates , ...
                        1 : endpoints , [2,4] , g , a , r));
                    allVNonVCU = toInd(allcomb(d , v , 1 : hpvVaxStates , 1 : hpvNonVaxStates , ...
                        1 : endpoints , 1 : intervens , g , a , r));
                
                    fracVaxd = sumall(pop(otherVCU)) / ...
                        sumall(pop(allVNonVCU)); % find proportion of population that is currently vaccinated
                    if vaxCoverCU(aV) - fracVaxd > 10 ^ -6 % when proportion vaccinated is below target vaccination level
                        vaxCover = max(0 , (vaxCoverCU(aV) - fracVaxd) ./ (1 - fracVaxd)); % vaccinate enough people in age group to reach target
                        vaxdGroupSus_noScrn = vaxCover .* pop(fromNonVSusCU_noScrn);
                        vaxdGroupSus_scrn = vaxCover .* pop(fromNonVSusCU_scrn);
                        vaxdGroupImm_noScrn = vaxCover .* pop(fromNonVImmCU_noScrn);
                        vaxdGroupImm_scrn = vaxCover .* pop(fromNonVImmCU_scrn);
                        vaxdGroupInf_noScrn = vaxCover .* pop(fromNonVInfCU_noScrn); % add vax of infected individuals
                        vaxdGroupInf_scrn = vaxCover .* pop(fromNonVInfCU_scrn); % add vax of infected individuals
                        vaxdGroupCin1_noScrn = vaxCover .* pop(fromNonVCin1CU_noScrn); % add vax of infected individuals
                        vaxdGroupCin1_scrn = vaxCover .* pop(fromNonVCin1CU_scrn); % add vax of infected individuals
                        vaxdGroupCin2_noScrn = vaxCover .* pop(fromNonVCin2CU_noScrn); % add vax of infected individuals
                        vaxdGroupCin2_scrn = vaxCover .* pop(fromNonVCin2CU_scrn); % add vax of infected individuals
                        vaxdGroupCin3_noScrn = vaxCover .* pop(fromNonVCin3CU_noScrn); % add vax of infected individuals
                        vaxdGroupCin3_scrn = vaxCover .* pop(fromNonVCin3CU_scrn); % add vax of infected individuals
                        vaxdGroupCc_noScrn = vaxCover .* pop(fromNonVCcCU_noScrn); % add vax of infected individuals
                        vaxdGroupCc_scrn = vaxCover .* pop(fromNonVCcCU_scrn); % add vax of infected individuals
                        
                        dPop(fromNonVSusCU_noScrn) = dPop(fromNonVSusCU_noScrn) - vaxdGroupSus_noScrn; % removed vaxd population from nonvaxd
                        dPop(fromNonVSusCU_scrn) = dPop(fromNonVSusCU_scrn) - vaxdGroupSus_scrn;
                        dPop(fromNonVImmCU_noScrn) = dPop(fromNonVImmCU_noScrn) - vaxdGroupImm_noScrn; 
                        dPop(fromNonVImmCU_scrn) = dPop(fromNonVImmCU_scrn) - vaxdGroupImm_scrn;
                        dPop(fromNonVInfCU_noScrn) = dPop(fromNonVInfCU_noScrn) - vaxdGroupInf_noScrn; % remove vax of infected individuals from pop
                        dPop(fromNonVInfCU_scrn) = dPop(fromNonVInfCU_scrn) - vaxdGroupInf_scrn; % remove vax of infected individuals from pop
                        dPop(fromNonVCin1CU_noScrn) = dPop(fromNonVCin1CU_noScrn) - vaxdGroupCin1_noScrn; % remove vax of infected individuals from pop
                        dPop(fromNonVCin1CU_scrn) = dPop(fromNonVCin1CU_scrn) - vaxdGroupCin1_scrn; % remove vax of infected individuals from pop
                        dPop(fromNonVCin2CU_noScrn) = dPop(fromNonVCin2CU_noScrn) - vaxdGroupCin2_noScrn; % remove vax of infected individuals from pop
                        dPop(fromNonVCin2CU_scrn) = dPop(fromNonVCin2CU_scrn) - vaxdGroupCin2_scrn; % remove vax of infected individuals from pop
                        dPop(fromNonVCin3CU_noScrn) = dPop(fromNonVCin3CU_noScrn) - vaxdGroupCin3_noScrn; % remove vax of infected individuals from pop
                        dPop(fromNonVCin3CU_scrn) = dPop(fromNonVCin3CU_scrn) - vaxdGroupCin3_scrn; % remove vax of infected individuals from pop
                        dPop(fromNonVCcCU_noScrn) = dPop(fromNonVCcCU_noScrn) - vaxdGroupCc_noScrn; % remove vax of infected individuals from pop
                        dPop(fromNonVCcCU_scrn) = dPop(fromNonVCcCU_scrn) - vaxdGroupCc_scrn; % remove vax of infected individuals from pop

                        dPop(toVSusCU_noScrn) = dPop(toVSusCU_noScrn) + vaxdGroupSus_noScrn;
                        dPop(toVSusCU_scrn) = dPop(toVSusCU_scrn) + vaxdGroupSus_scrn;
                        dPop(toVImmCU_noScrn) = dPop(toVImmCU_noScrn) + vaxdGroupImm_noScrn;
                        dPop(toVImmCU_scrn) = dPop(toVImmCU_scrn) + vaxdGroupImm_scrn;
                        dPop(toVInfCU_noScrn) = dPop(toVInfCU_noScrn) + vaxdGroupInf_noScrn; % move to vaxxed comp
                        dPop(toVInfCU_scrn) = dPop(toVInfCU_scrn) + vaxdGroupInf_scrn; % move to vaxxed comp
                        dPop(toVCin1CU_noScrn) = dPop(toVCin1CU_noScrn) + vaxdGroupCin1_noScrn; % move to vaxxed comp
                        dPop(toVCin1CU_scrn) = dPop(toVCin1CU_scrn) + vaxdGroupCin1_scrn; % move to vaxxed comp
                        dPop(toVCin2CU_noScrn) = dPop(toVCin2CU_noScrn) + vaxdGroupCin2_noScrn; % move to vaxxed comp
                        dPop(toVCin2CU_scrn) = dPop(toVCin2CU_scrn) + vaxdGroupCin2_scrn; % move to vaxxed comp
                        dPop(toVCin3CU_noScrn) = dPop(toVCin3CU_noScrn) + vaxdGroupCin3_noScrn; % move to vaxxed comp
                        dPop(toVCin3CU_scrn) = dPop(toVCin3CU_scrn) + vaxdGroupCin3_scrn; % move to vaxxed comp
                        dPop(toVCcCU_noScrn) = dPop(toVCcCU_noScrn) + vaxdGroupCc_noScrn; % move to vaxxed comp
                        dPop(toVCcCU_scrn) = dPop(toVCcCU_scrn) + vaxdGroupCc_scrn; % move to vaxxed comp
                        
                        hpvVaxd = hpvVaxd + sumall(vaxdGroupSus_noScrn) + ...
                            sumall(vaxdGroupSus_scrn) + sumall(vaxdGroupImm_noScrn) + ...
                            sumall(vaxdGroupImm_scrn) + sumall(vaxdGroupInf_scrn) + ...
                            sumall(vaxdGroupInf_noScrn) + ...
                            sumall(vaxdGroupCin1_scrn) + sumall(vaxdGroupCin1_noScrn) + ...
                            sumall(vaxdGroupCin2_scrn) + sumall(vaxdGroupCin2_noScrn) + ...
                            sumall(vaxdGroupCin3_scrn) + sumall(vaxdGroupCin3_noScrn) + ...
                            sumall(vaxdGroupCc_scrn) + sumall(vaxdGroupCc_noScrn); % count number of people vaccinated at current time step
                        hpvVaxdPrev = hpvVaxdPrev + sumall(vaxdGroupInf_scrn) + ...
                            sumall(vaxdGroupInf_noScrn) + ...
                            sumall(vaxdGroupCin1_scrn) + sumall(vaxdGroupCin1_noScrn) + ...
                            sumall(vaxdGroupCin2_scrn) + sumall(vaxdGroupCin2_noScrn) + ...
                            sumall(vaxdGroupCin3_scrn) + sumall(vaxdGroupCin3_noScrn) + ...
                            sumall(vaxdGroupCc_scrn) + sumall(vaxdGroupCc_noScrn); 
                        hpvVaxdNonPrev = hpvVaxdNonPrev + sumall(vaxdGroupSus_noScrn) + ...
                            sumall(vaxdGroupSus_scrn) + sumall(vaxdGroupImm_noScrn) + ...
                            sumall(vaxdGroupImm_scrn); 
                    end

                end
            end
        end
    end
end

%% Convert dPop to a column vector for output to ODE solver
dPop = sparse(dPop);