function parsave(fname, fivYrAgeGrpsOn , tVec , popVec , newHiv , transCD4 , ...
    newHpvVax , newImmHpvVax , newHpvNonVax , newImmHpvNonVax , ...
    hivDeaths , deaths , ccDeath , ...
    newCC , menCirc , vaxdLmtd , vaxdSchool , vaxdCU , newScreen , artDist , artDistList , artTreatTracker , ...
    newTreatImm , newTreatHpv , newTreatHyst , ...
    nHivDiagVec , nHivUndiagVec , nTestedNeg , nTestedUndiag , propHivDiag , ...
    currYear , lastYear , vaxRate , vaxEff , popLast , pathModifier)

savDir = [pwd , '/HHCoM_Results/Vaccine' , pathModifier, '/'];
save(fullfile(savDir , fname) , 'fivYrAgeGrpsOn' , 'tVec' ,  'popVec' , ...
    'newHiv' , 'transCD4' , ...
    'newHpvVax' , 'newImmHpvVax' , 'newHpvNonVax' , 'newImmHpvNonVax' , ...
    'hivDeaths' , 'deaths' , 'ccDeath' , ...
    'newCC' , 'menCirc' , 'vaxdLmtd' , 'vaxdSchool' , 'vaxdCU' , 'newScreen' , 'artDist' , 'artDistList' , 'artTreatTracker' , ...
    'newTreatImm' , 'newTreatHpv' , 'newTreatHyst' , ...
    'nHivDiagVec' , 'nHivUndiagVec' , 'nTestedNeg' , 'nTestedUndiag' , 'propHivDiag' , ...
    'currYear' , 'lastYear' , 'vaxRate' , 'vaxEff' , 'popLast' , '-v7.3') 
end
