function parsave(fname , tVec ,  popVec , newHiv ,...
    newImmHpv , newVaxHpv , newHpv , hivDeaths , ...
    deaths , newCC , artTreatTracker , startYear , endYear , popLast)

savdir = 'H:\HHCoM_Results';
save(fullfile(savdir , fname) , 'tVec' ,  'popVec' , 'newHiv' ,...
    'newImmHpv' , 'newVaxHpv' , 'newHpv' , 'hivDeaths' , ...
    'deaths' , 'newCC' , 'artTreatTracker' , 'startYear' , 'endYear' , 'popLast' ,'-v7.3')

end
