function [] = vaxCEA_multSims_CIs_pHIV(vaxResultInd , sceNum , fileNameNums)
% example: vaxCEA_multSims_CIs_pHIV(1 , '0' , {'0' , '_'})

%% Load parameters and results
paramDir = [pwd , '\Params\'];

[stepsPerYear , timeStep , startYear , currYear , endYear , ...
    years , disease , viral , hpvVaxStates , hpvNonVaxStates , endpoints , ...
    intervens , gender , age , risk , hpvTypeGroups , dim , k , toInd , ...
    annlz , ...
    ageSexDebut , mInit , fInit , partnersM , partnersF , maleActs , ...
    femaleActs , riskDist , fertility , fertility2 , fertility3 , fertility4 , ...
    mue , mue2 , mue3 , mue4 , epsA_vec , epsR_vec , ...
    yr , ...
    hivOn , betaHIV_mod , muHIV , kCD4 , ...
    hpvOn , beta_hpvVax_mod , beta_hpvNonVax_mod , fImm , rImmune , ...
    kCin1_Inf , kCin2_Cin1 , kCin3_Cin2 , kCC_Cin3 , rNormal_Inf , kInf_Cin1 , ...
    kCin1_Cin2 , kCin2_Cin3 , lambdaMultImm , hpv_hivClear , rImmuneHiv , ...
    c3c2Mults , c2c1Mults , c2c3Mults , c1c2Mults , muCC , kRL , kDR , artHpvMult , ...
    hpv_hivMult , maleHpvClearMult , ...
    condUse , screenYrs , hpvScreenStartYear , ...
    artYr , maxRateM , maxRateF , ...
    artYr_vec , artM_vec , artF_vec , minLim , maxLim , ...
    circ_aVec , vmmcYr_vec , vmmc_vec , vmmcYr , vmmcRate , ...
    hivStartYear , circStartYear , circNatStartYear , vaxStartYear , ...
    baseline , who , spCyto , spHpvDna , spGentyp , spAve , spHpvAve , ...
    circProtect , condProtect , MTCTRate , hyst , ...
    OMEGA , ...
    ccInc2012_dObs , ccInc2018_dObs , cc_dist_dObs , cin3_dist_dObs , ...
    cin1_dist_dObs , hpv_dist_dObs , cinPos2002_dObs , cinNeg2002_dObs , ...
    cinPos2015_dObs , cinNeg2015_dObs , hpv_hiv_dObs , hpv_hivNeg_dObs , ...
    hpv_hivM2008_dObs , hpv_hivMNeg2008_dObs , hivPrevM_dObs , hivPrevF_dObs , ...
    popAgeDist_dObs , totPopSize_dObs , ...
    hivCurr , ...
    gar , hivSus , hpvVaxSus , hpvVaxImm , hpvNonVaxSus , hpvNonVaxImm , ...
    toHiv , vaxInds , nonVInds , hpvVaxInf , hpvNonVaxInf , ...
    hivInds , ...
    cin3hpvVaxIndsFrom , ccLochpvVaxIndsTo , ccLochpvVaxIndsFrom , ...
    ccReghpvVaxInds , ccDisthpvVaxInds , cin3hpvNonVaxIndsFrom , ...
    ccLochpvNonVaxIndsTo , ccLochpvNonVaxIndsFrom , ccReghpvNonVaxInds , ...
    ccDisthpvNonVaxInds , cin1hpvVaxInds , cin2hpvVaxInds , cin3hpvVaxInds , ...
    cin1hpvNonVaxInds , cin2hpvNonVaxInds , cin3hpvNonVaxInds , normalhpvVaxInds , ...
    immunehpvVaxInds , infhpvVaxInds , normalhpvNonVaxInds , immunehpvNonVaxInds , ...
    infhpvNonVaxInds , fromVaxNoScrnInds , fromVaxScrnInds , toNonVaxNoScrnInds , ...
    toNonVaxScrnInds , ageInd , riskInd , ...
    hivNegNonVMMCinds , hivNegVMMCinds , ...
    vlAdvancer , ...
    fertMat , hivFertPosBirth , hivFertNegBirth , fertMat2 , ...
    hivFertPosBirth2 , hivFertNegBirth2 , fertMat3 , hivFertPosBirth3 , hivFertNegBirth3 , ...
    fertMat4 , hivFertPosBirth4 , hivFertNegBirth4 , ...
    dFertPos1 , dFertNeg1 , dFertMat1 , dFertPos2 , dFertNeg2 , dFertMat2 , ...
    dFertPos3 , dFertNeg3 , dFertMat3 , deathMat , deathMat2 , deathMat3 , deathMat4 , ...
    dDeathMat , dDeathMat2 , dDeathMat3 , dMue] = loadUp2(1 , 0 , [] , [] , []);

% Plot settings
reset(0)
set(0 , 'defaultlinelinewidth' , 1.5)

lastYear = 2122;  % ***SET ME***: last year of simulation (use 2022 for SA screening analysis)

% Indices of calib runs to plot
fileInds = {'6_1' , '6_2' , '6_3' , '6_6' , '6_8' , '6_9' , '6_11' , ...
     '6_12' , '6_13' , '6_15' , '6_20' , '6_21' , '6_22' , '6_26' , ...
    '6_27' , '6_32' , '6_34' , '6_35' , '6_38' , '6_39' , '6_40' , ...
    '6_41' , '6_42' , '6_45' , '6_47'};    % 22Apr20Ph2V11
nRuns = length(fileInds);

% Initialize model output vectors
% Timespans
monthlyTimespan = [startYear : timeStep : lastYear];
monthlyTimespan = monthlyTimespan(1 : end-1);
annualTimespan = [startYear : lastYear-1];
% HIV prevalence
hivPrevW = zeros(nRuns , length(monthlyTimespan));
% Cervical cancer
diseaseVec_ccInc = {[1 : disease] , [1 : 2] , [3 : 7] , 8 , [3 : 8]};
diseaseLabels = {'General' , 'HIV-' , 'HIV+untreated' , 'HIV+ART' , 'HIV+all'};
diseaseVecLength_ccInc = length(diseaseVec_ccInc);
ccIncHivTime = zeros(nRuns , 5 , length(annualTimespan));
ccIncHivAgeTime = zeros(nRuns , 5 , age , length(annualTimespan));
ccAnnlHivTime = zeros(nRuns , 5 , length(annualTimespan));

n = vaxResultInd;
baseFileName = ['22Apr20Ph2V11_2v57BaseVax_spCytoScreen_noVMMChpv_hivInt2017_pHIV-S' , sceNum , '_']; % ***SET ME***: name for simulation output file
loopSegments = {0 , round(nRuns/2) , nRuns};
loopSegmentsLength = length(loopSegments);
for k = 1 : loopSegmentsLength-1
    parfor j = loopSegments{k}+1 : loopSegments{k+1}
        % Load results
        pathModifier = [baseFileName , fileInds{j}];
        nSims = size(dir([pwd , '\HHCoM_Results\' , pathModifier, '\' , '*.mat']) , 1);
        curr = load([pwd , '/HHCoM_Results/toNow_22Apr20Ph2V11_2v57BaseVax_spCytoScreen_noVMMChpv_hivInt2017_' , fileInds{j}]); % ***SET ME***: name for historical run output file 

        vaxResult = cell(nSims , 1);
        resultFileName = [pwd , '\HHCoM_Results\' , pathModifier, '\' , 'vaxSimResult'];
        % load results from vaccine run into cell array
        vaxResult{n} = load([resultFileName , num2str(n), '.mat']);
        % concatenate vectors/matrices of population up to current year to population
        % matrices for years past current year
        vaxResult{n}.popVec = [curr.popVec(1 : end  , :); vaxResult{n}.popVec(2 : end , :)];
        vaxResult{n}.newCC = [curr.newCC(1 : end , : , : , :); vaxResult{n}.newCC(2 : end , : , : , :)];
        vaxResult{n}.newHiv = [curr.newHiv(1 : end , : , : , : , : , : , :); vaxResult{n}.newHiv(2 : end , : , : , : , : , : , :)];
        vaxResult{n}.tVec = [curr.tVec(1 : end), vaxResult{n}.tVec(2 : end)];
        tVec = vaxResult{n}.tVec;

        %% ***************************** HIV AND HIV TREATMENT OUTCOMES ******************************************************************************

        %% HIV prevalence in women aged 15+ over time
        hivInds = toInd(allcomb(3 : 8 , 1 : viral , 1 : hpvVaxStates , 1 : hpvNonVaxStates , 1 : endpoints , ...
            1 : intervens , 2 , 4 : age , 1 : risk));
        totInds = toInd(allcomb(1 : disease , 1 : viral , 1 : hpvVaxStates , 1 : hpvNonVaxStates , 1 : endpoints , ...
            1 : intervens , 2 , 4 : age , 1 : risk));
        hivPrevW(j , :) = (sum(vaxResult{n}.popVec(: , hivInds) , 2) ./ sum(vaxResult{n}.popVec(: , totInds) , 2));
        
        %% ****************************** CERVICAL CANCER OUTCOMES ****************************************************************************************
    
        %% Cervical cancer incidence by HIV status over time
        fac = 10 ^ 5;
        for dInd = 1 : diseaseVecLength_ccInc
            d = diseaseVec_ccInc{dInd};
            allF = toInd(allcomb(d , 1 : viral , 1 : hpvVaxStates , 1 : hpvNonVaxStates , ...
                1 : endpoints , 1 : intervens , 2 , 1 : age , 1 : risk));
            ccIncHivTime(j , dInd , :) = ...
                (annlz(sum(sum(sum(vaxResult{n}.newCC(: , d , 3 : age , :),2),3),4)) ./ ...
                (annlz(sum(vaxResult{n}.popVec(: , allF) , 2) ./ stepsPerYear)) * fac);
        end
        
        %% Cervical cancer incidence by HIV status and age over time
        fac = 10 ^ 5;
        for dInd = 1 : diseaseVecLength_ccInc
            d = diseaseVec_ccInc{dInd};
            for a = 1 : age
                allF = toInd(allcomb(d , 1 : viral , 1 : hpvVaxStates , 1 : hpvNonVaxStates , ...
                    1 : endpoints , 1 : intervens , 2 , a , 1 : risk));
                ccIncHivAgeTime(j , dInd , a , :) = ...
                    (annlz(sum(sum(sum(vaxResult{n}.newCC(: , d , a , :),2),3),4)) ./ ...
                    (annlz(sum(vaxResult{n}.popVec(: , allF) , 2) ./ stepsPerYear)) * fac);
            end
        end
        
        %% Cumulative cervical cancer cases by HIV status over time
        for dInd = 1 : diseaseVecLength_ccInc
            d = diseaseVec_ccInc{dInd};
                ccCumHivTime(j , dInd , :) = ...
                    cumsum(squeeze(annlz(sum(sum(sum(vaxResult{n}.newCC(((currYear - startYear) * stepsPerYear +1):end , d , : , :),2),3),4))),2);
        end
        
        %% Annual cervical cancer cases by HIV status over time
        for dInd = 1 : diseaseVecLength_ccInc
            d = diseaseVec_ccInc{dInd};
            ccAnnlHivTime(j , dInd , :) = ...
                annlz(sum(sum(sum(vaxResult{n}.newCC(: , d , : , :),2),3),4));
        end
        
     end
end

%% ***************************** HIV AND HIV TREATMENT OUTCOMES ******************************************************************************

%% Write crude HIV prevalence in women aged 15+ over time
fname = [pwd , '\HHCoM_Results\' , baseFileName , fileInds{1} , '\' , ...
     'PAF_crudeHivFaged15plus_' , fileNameNums{vaxResultInd} , '.xlsx'];
firstYrInd = ((1980 - startYear)*stepsPerYear +1);
writematrix([[1980 : lastYear-1]' , ...
    squeeze(median(squeeze(hivPrevW(: , (firstYrInd:stepsPerYear:end))) , 1))' , ...
    squeeze(min(squeeze(hivPrevW(: , (firstYrInd:stepsPerYear:end))) , [] , 1))' , ...
    squeeze(max(squeeze(hivPrevW(: , (firstYrInd:stepsPerYear:end))) , [] , 1))' , ...
    squeeze(hivPrevW(: , (firstYrInd:stepsPerYear:end)))'] , fname);


%% ****************************** CERVICAL CANCER OUTCOMES ****************************************************************************************

%% Write crude cervical cancer incidence by HIV status over time
fname = [pwd , '\HHCoM_Results\' , baseFileName , fileInds{1} , '\' , ...
    'PAF_crudeICC_' , fileNameNums{vaxResultInd} , '.xlsx'];
firstYrInd = ((1980 - startYear) +1);
for dInd = 1 : diseaseVecLength_ccInc   
    writematrix([[1980 : lastYear-1]' , ...
        squeeze(median(squeeze(ccIncHivTime(: , dInd , firstYrInd:end)) , 1))' , ...
        squeeze(min(squeeze(ccIncHivTime(: , dInd , firstYrInd:end)) , [] , 1))' , ...
        squeeze(max(squeeze(ccIncHivTime(: , dInd , firstYrInd:end)) , [] , 1))' , ...
        squeeze(ccIncHivTime(: , dInd , firstYrInd:end))'] , ...
        fname , 'Sheet' , diseaseLabels{dInd});
end

%% Write age-standardized cervical cancer incidence by HIV status over time
% Note: the age-standardization process shifts the incidence rate of the
% last modelled age group to the next age group in the following year.
% However, CC incidence is NaN prior to HIV introduction in the
% HIV-positive no ART group, and NaN prior to ART introduction in the
% HIV-positive ART group. Since we have four age groups past the 16 we
% model, a NaN value is present for four years past the introduction of
% HIV/ART, leading to a NaN value for summed incidence during these 
% years. We therefore lack data in this four-year interval in the
% saved/plotted results.
fac = 10 ^ 5;
worldStandard_WP2015 = [325428 311262 295693 287187 291738 299655 272348 ...
    247167 240167 226750 201603 171975 150562 113118 82266 64484 42237 ...
    23477 9261 2155];
fname = [pwd , '\HHCoM_Results\' , baseFileName , fileInds{1} , '\' , ...
    'PAF_ASICC_' , fileNameNums{vaxResultInd} , '.xlsx'];
firstYrRange = (lastYear-1) - 1980;
for dInd = 1 : length(diseaseLabels)
    ccIncHivAgeTime_dis = squeeze(ccIncHivAgeTime(: , dInd , : , :));

    ccIncRefTot = zeros(size(ccIncHivAgeTime_dis,1) , 1 , size(ccIncHivAgeTime_dis,3));       
    for aInd = 1:age+4
        a = aInd;
        if aInd >= age
            a = age;
        end

        if aInd <= age    
            ccIncRef = ccIncHivAgeTime_dis(: , a , :) .* worldStandard_WP2015(aInd);
            if (a < 3)
                ccIncRef = zeros(size(ccIncHivAgeTime_dis,1) , 1 , size(ccIncHivAgeTime_dis,3));
            end
        elseif aInd > age
            ccIncRef = ccIncHivAgeTime_dis(: , a , :);
            ccIncRef = cat(3 , (ones(size(ccIncRef,1),1,aInd-a).*ccIncRef(:,1,1)) , ccIncRef(: , 1 ,1:end-(aInd-a)));
            ccIncRef = ccIncRef .* worldStandard_WP2015(aInd);
        end
        ccIncRefTot = ccIncRefTot + ccIncRef;
    end
    ccInc = ccIncRefTot ./ (sum(worldStandard_WP2015(1:age+4)));

    writematrix([[1980 : lastYear-1]' , ...
        squeeze(median(squeeze(ccInc(: , : , (end-firstYrRange):end)) , 1))' , ...
        squeeze(min(squeeze(ccInc(: , : , (end-firstYrRange):end)) , [] , 1))' , ...
        squeeze(max(squeeze(ccInc(: , : , (end-firstYrRange):end)) , [] , 1))' , ...
        squeeze(ccInc(: , : , (end-firstYrRange):end))'] , ...
        fname , 'Sheet' , diseaseLabels{dInd}); 
end

%% Write annual cervical cancer cases by HIV status over time
fname = [pwd , '\HHCoM_Results\' , baseFileName , fileInds{1} , '\' , ...
    'PAF_crudeAnnualCC_' , fileNameNums{vaxResultInd} , '.xlsx'];
firstYrInd = ((1980 - startYear) +1);
for dInd = 1 : diseaseVecLength_ccInc   
    writematrix([[1980 : lastYear-1]' , ...
        squeeze(median(squeeze(ccAnnlHivTime(: , dInd , firstYrInd:end)) , 1))' , ...
        squeeze(min(squeeze(ccAnnlHivTime(: , dInd , firstYrInd:end)) , [] , 1))' , ...
        squeeze(max(squeeze(ccAnnlHivTime(: , dInd , firstYrInd:end)) , [] , 1))' , ...
        squeeze(ccAnnlHivTime(: , dInd , firstYrInd:end))'] , ...
        fname , 'Sheet' , diseaseLabels{dInd});
end

