%function vaxCEA_multSims_CISNETsces()

%% LOAD PARAMETERS
paramDir = [pwd , '\Params\'];

[stepsPerYear , timeStep , startYear , currYear , endYear , ...
    years , disease , viral , hpvVaxStates , hpvNonVaxStates , endpoints , ...
    intervens , gender , age , risk , hpvTypeGroups , dim , k , toInd , ...
    annlz , ...
    ageSexDebut , mInit , fInit , partnersM , partnersF , maleActs , ...
    femaleActs , riskDist , fertility , fertility2 , fertility3 , fertility4 , ...
    mue , mue2 , mue3 , mue4 , epsA_vec , epsR_vec , ...
    yr , ...
    hivOn , betaHIV_mod , muHIV , kCD4 , ...
    hpvOn , beta_hpvVax_mod , beta_hpvNonVax_mod , fImm , rImmune , ...
    kCin1_Inf , kCin2_Cin1 , kCin3_Cin2 , kCC_Cin3 , rNormal_Inf , kInf_Cin1 , ...
    kCin1_Cin2 , kCin2_Cin3 , lambdaMultImm , hpv_hivClear , rImmuneHiv , ...
    c3c2Mults , c2c1Mults , c2c3Mults , c1c2Mults , muCC , kRL , kDR , artHpvMult , ...
    hpv_hivMult , maleHpvClearMult , ...
    condUse , screenYrs , hpvScreenStartYear , ...
    artYr , maxRateM , maxRateF , ...
    artYr_vec , artM_vec , artF_vec , minLim , maxLim , ...
    circ_aVec , vmmcYr_vec , vmmc_vec , vmmcYr , vmmcRate , ...
    hivStartYear , circStartYear , circNatStartYear , vaxStartYear , ...
    baseline , who , spCyto , spHpvDna , spGentyp , spAve , spHpvAve , ...
    circProtect , condProtect , MTCTRate , hyst , ...
    OMEGA , ...
    ccInc2012_dObs , ccInc2018_dObs , cc_dist_dObs , cin3_dist_dObs , ...
    cin1_dist_dObs , hpv_dist_dObs , cinPos2002_dObs , cinNeg2002_dObs , ...
    cinPos2015_dObs , cinNeg2015_dObs , hpv_hiv_dObs , hpv_hivNeg_dObs , ...
    hpv_hivM2008_dObs , hpv_hivMNeg2008_dObs , hivPrevM_dObs , hivPrevF_dObs , ...
    popAgeDist_dObs , totPopSize_dObs , ...
    hivCurr , ...
    gar , hivSus , hpvVaxSus , hpvVaxImm , hpvNonVaxSus , hpvNonVaxImm , ...
    toHiv , vaxInds , nonVInds , hpvVaxInf , hpvNonVaxInf , ...
    hivInds , ...
    cin3hpvVaxIndsFrom , ccLochpvVaxIndsTo , ccLochpvVaxIndsFrom , ...
    ccReghpvVaxInds , ccDisthpvVaxInds , cin3hpvNonVaxIndsFrom , ...
    ccLochpvNonVaxIndsTo , ccLochpvNonVaxIndsFrom , ccReghpvNonVaxInds , ...
    ccDisthpvNonVaxInds , cin1hpvVaxInds , cin2hpvVaxInds , cin3hpvVaxInds , ...
    cin1hpvNonVaxInds , cin2hpvNonVaxInds , cin3hpvNonVaxInds , normalhpvVaxInds , ...
    immunehpvVaxInds , infhpvVaxInds , normalhpvNonVaxInds , immunehpvNonVaxInds , ...
    infhpvNonVaxInds , fromVaxNoScrnInds , fromVaxScrnInds , toNonVaxNoScrnInds , ...
    toNonVaxScrnInds , ageInd , riskInd , ...
    hivNegNonVMMCinds , hivNegVMMCinds , ...
    vlAdvancer , ...
    fertMat , hivFertPosBirth , hivFertNegBirth , fertMat2 , ...
    hivFertPosBirth2 , hivFertNegBirth2 , fertMat3 , hivFertPosBirth3 , hivFertNegBirth3 , ...
    fertMat4 , hivFertPosBirth4 , hivFertNegBirth4 , ...
    dFertPos1 , dFertNeg1 , dFertMat1 , dFertPos2 , dFertNeg2 , dFertMat2 , ...
    dFertPos3 , dFertNeg3 , dFertMat3 , deathMat , deathMat2 , deathMat3 , deathMat4 , ...
    dDeathMat , dDeathMat2 , dDeathMat3 , dMue] = loadUp2(1 , 0 , [] , [] , []);

%% LOAD SAVED RESULTS

% ***SET ME***: save names of potential scenarios to analyze as variables
baseDirName = 'Vaccine22Apr20Ph2V11_2v57BaseVax_spCytoScreen_hpvHIVcalib_adjFert2_adjCCAgeMults3_KZNCC4_noVMMChpv_CISNET-S';
dirName_S0 = [baseDirName , '0_6_1'];
dirName_S1 = [baseDirName , '1_6_1'];
dirName_S2 = [baseDirName , '2_6_1'];

% ***SET ME***: choose which scenarios you want to save data in Excel for
simVec = {dirName_S0 , dirName_S1 , dirName_S2};
fileVec = {'0' , '1' , '2'}; 
colorVec = {[0 0.4470 0.7410] , [0.4660 , 0.6740 , 0.1880] , [0.8500 0.3250 0.0980]}; 
% ***SET ME***: make sure the names here correspond to scenarios in simVec above
fileTits = {'No HIV', 'HIV, no ART' , 'HIV, observed ART, no scale-up'};
fileTits2 = {'CIN1' , 'HPV+ (no CIN)' , 'HPV-susceptible' , 'HIV-negative' , 'HIV-positive, untreated' , 'HIV-positive on ART'};
nResults = length(simVec);

% Plot settings
reset(0)
set(0 , 'defaultlinelinewidth' , 1.5)


%% Crude HPV prevalence over time
fig = figure;
set(fig,'DefaultAxesFontSize' , 18);
t82on = (1982:2120)';
t82onLen = length(t82on);
for j = 1 : nResults  
    for dInd = 1 : 1 %5
        % Load results
        fname = [pwd , '\HHCoM_Results\' , simVec{j} , '\' , ...
            'ART_comparative_modeling_outcome_templates_020221-fullData.xlsx'];
        hpvPrevTime = readmatrix(fname , 'Sheet' , 'HPVprev-Crude' , 'Range' , ['C' , num2str(((dInd-1)*t82onLen+1)) , ':C' , num2str(dInd*t82onLen)]);
        hold all;
        p = plot(t82on , hpvPrevTime , 'Color' , colorVec{j});
%         hold all;
%         x2 = [ccIncHivTime(: , 1)' , fliplr(ccIncHivTime(: , 1)')];
%         inBetween = [ccIncHivTime(: , 4)' , fliplr(ccIncHivTime(: , 3)')];
%         colorP = get(p,'Color');
%         h = fill(x2 , inBetween , colorP);
%         h.FaceAlpha = 0.3;
%         h.LineStyle = '--';
    end
end

legend(fileTits{:} , 'Location' , 'northeast');
xlim([1980 2120]); ylim([0 0.2]);
grid on;
xlabel('Year'); ylabel('Crude HPV prevalence');

%% Age-standardized HPV prevalence over time
fig = figure;
set(fig,'DefaultAxesFontSize' , 18);
t82on = (1982:2120)';
t82onLen = length(t82on);
for j = 1 : nResults  
    for dInd = 1 : 1 %5
        % Load results
        fname = [pwd , '\HHCoM_Results\' , simVec{j} , '\' , ...
            'ART_comparative_modeling_outcome_templates_020221-fullData.xlsx'];
        hpvPrevTime = readmatrix(fname , 'Sheet' , 'HPVprev-AS' , 'Range' , ['C' , num2str(((dInd-1)*t82onLen+1)) , ':C' , num2str(dInd*t82onLen)]);
        hold all;
        p = plot(t82on , hpvPrevTime , 'Color' , colorVec{j});
%         hold all;
%         x2 = [ccIncHivTime(: , 1)' , fliplr(ccIncHivTime(: , 1)')];
%         inBetween = [ccIncHivTime(: , 4)' , fliplr(ccIncHivTime(: , 3)')];
%         colorP = get(p,'Color');
%         h = fill(x2 , inBetween , colorP);
%         h.FaceAlpha = 0.3;
%         h.LineStyle = '--';
    end
end

legend(fileTits{:} , 'Location' , 'northeast');
xlim([1980 2120]); ylim([0 0.2]);
grid on;
xlabel('Year'); ylabel('AS-HPV prevalence');




